apiVersion: rtf.mulesoft.com/v1alpha1
kind: MuleApplication
metadata:
  labels:
  name: mule-sample
  namespace: ci
spec:
  target: jeff-rtf
  businessGroup: mulesoft
  environment: Sandbox2
  clustered: true
  runtimeVersion: 4.6.16:2-java8
  resources:
    requests:
      cpu: 1000m
      memory: 700Mi
    limits:
      cpu: 5000m
      memory: 2700Mi
  replicas: 2
  application:
    ref:
      groupId: 1fbd2e46-128a-478c-a5fb-c03a655f82cd
      artifactId: os-test-1.0.0-mule-application
      version: "1.0.0"
      packaging: jar
  properties:
  - name: truststore.path
    value: /var/tls/clienttruststore.jks
  - name: keystore.path
    value: /var/tls/example2.com.p12
  - name: my-greeting
    value: hello world
  propertiesFrom:
  - secretRef:
      name: keystore-passwords
  volumes:
  - name: javakeystore
    secret:
      secretName: javakeystore
  volumeMounts:
  - name: javakeystore
    mountPath: /var/tls
    readOnly: true
