apiVersion: rtf.mulesoft.com/v1alpha1
kind: MuleApplication
metadata:
  labels:
  name: mule-sample
  namespace: ack-test
spec:
  target: jeff-rtf
  businessGroup: mulesoft
  environment: Sandbox2
  clustered: false
  runtimeVersion: 4.6.16:2-java8
  resources:
    requests:
      cpu: 20m
      memory: 700Mi
    limits:
      cpu: 4000m
      memory: 2700Mi
  replicas: 1
  application:
    ref:
      groupId: 1fbd2e46-128a-478c-a5fb-c03a655f82cd
      artifactId: os-test-1.0.0-mule-application
      version: "1.0.0"
      packaging: jar
  properties:
  - name: truststore.path
    value: /var/tls/clienttruststore.jks
  - name: keystore.path
    value: /var/tls/example2.com.p12
  - name: a
    value: c
  propertiesFrom:
  - secretRef:
      name: keystore-passwords
  volumes:
  # - name: aws-secrets-volume
  #   csi:
  #     driver: secrets-store.csi.k8s.io
  #     readOnly: true
  #     volumeAttributes:
  #       secretProviderClass: aws-secrets
  - name: javakeystore
    secret:
      secretName: javakeystore
  volumeMounts:
  # - name: aws-secrets-volume
  #   mountPath: /var/config/aws
  #   readOnly: true
  - name: javakeystore
    mountPath: /var/tls
    readOnly: true
